HOSTS:
  slurm-controller:
    roles:
      - master
      - agent
      - dashboard
      - database
      - slurm_controller
    platform: el-6-x86_64
    box: centos-65-x64-virtualbox-nocm
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor: vagrant
    ip: 192.168.1.2
  slurm-node1:
    roles:
      - agent
      - slurm_node
    platform: el-6-x86_64
    box: centos-65-x64-virtualbox-nocm
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor: vagrant
    ip: 192.168.1.3
  slurm-node2:
    roles:
      - agent
      - slurm_node
    platform: el-6-x86_64
    box: centos-65-x64-virtualbox-nocm
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor: vagrant
    ip: 192.168.1.4
  slurm-client:
    roles:
      - agent
      - slurm_client
    platform: el-6-x86_64
    box: centos-65-x64-virtualbox-nocm
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor: vagrant
    ip: 192.168.1.5
CONFIG:
  log_level: debug
  type: foss